name: dp3_rtx
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.4=h7354ed3_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.19=h1b28b03_0
  - packaging=25.0=py310h06a4308_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - asciitree==0.3.3
      - asttokens==3.0.1
      - attrs==25.4.0
      - av==16.1.0
      - blessed==1.29.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.2
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.2.2
      - cycler==0.12.1
      - decorator==4.4.2
      - diffusers==0.11.1
      - diffusion-policy-3d==0.0.0
      - dill==0.3.5.1
      - dm-control==1.0.36
      - dm-env==1.6
      - dm-tree==0.1.9
      - einops==0.4.1
      - etils==1.13.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fasteners==0.20
      - filelock==3.20.3
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.46
      - glfw==2.10.0
      - gpustat==1.1.1
      - gym==0.21.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.25.2
      - hydra-core==1.2.0
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - iopath==0.1.10
      - ipdb==0.13.13
      - ipython==8.38.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - labmaze==1.0.6
      - llvmlite==0.39.1
      - lxml==6.0.2
      - markupsafe==3.0.2
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - moviepy==1.0.3
      - mpmath==1.3.0
      - mujoco==3.4.0
      - networkx==3.4.2
      - numba==0.56.4
      - numcodecs==0.13.1
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.17.1.4
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.590.48
      - nvidia-nccl-cu12==2.28.9
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.3.0
      - pip==23.3.2
      - platformdirs==4.5.1
      - portalocker==3.2.0
      - proglog==0.1.12
      - prompt-toolkit==3.0.52
      - protobuf==6.33.5
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybullet==3.2.7
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyopengl==3.1.10
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - scipy==1.15.3
      - sentry-sdk==2.51.0
      - setuptools==65.5.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - termcolor==3.3.0
      - tomli==2.4.0
      - torch==2.11.0.dev20260202+cu128
      - torchaudio==2.11.0.dev20260202+cu128
      - torchvision==0.25.0.dev20260202+cu128
      - tqdm==4.67.2
      - traitlets==5.14.3
      - triton==3.6.0+git9844da95
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - wandb==0.24.1
      - wcwidth==0.5.3
      - wheel==0.38.4
      - wrapt==2.1.0
      - yacs==0.1.8
      - zarr==2.12.0
      - zipp==3.23.0
prefix: /home/mlewkowicz/anaconda3/envs/dp3_rtx
